apiVersion: v1
kind: Service
metadata:
  name: pages
spec:
  type: NodePort
  selector:
    app: pages
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pages
spec:
  selector:
    matchLabels:
      app: pages
  template:
    metadata:
      labels:
        app: pages
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pages
      containers:
      - name: pages
        image: 192.168.50.182:30082/gssjl2008/pages:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30

