# Generated by Django 3.2.3 on 2021-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page_info',
            fields=[
                ('p_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键')),
                ('p_name', models.CharField(max_length=10, verbose_name='页面名称')),
                ('p_desc', models.CharField(max_length=100, verbose_name='页面描述')),
                ('p_src', models.CharField(max_length=100, verbose_name='页面链接')),
                ('p_gov', models.CharField(default='官方地址', max_length=100, verbose_name='官网地址')),
                ('p_gov_src', models.CharField(max_length=100, verbose_name='官网链接')),
                ('p_doc', models.CharField(blank=True, max_length=100, null=True, verbose_name='帮助文档')),
                ('p_doc_src', models.CharField(blank=True, max_length=100, null=True, verbose_name='官方文档链接')),
            ],
        ),
    ]
