# Generated by Django 3.2.3 on 2021-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_info',
            options={'verbose_name': '页面信息', 'verbose_name_plural': '页面全部信息'},
        ),
        migrations.AddField(
            model_name='page_info',
            name='p_stats',
            field=models.CharField(choices=[(0, 'off'), (1, 'on')], default=0, max_length=1, verbose_name='页面状态'),
        ),
    ]
