# Generated by Django 3.2.3 on 2021-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0002_auto_20210524_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_info',
            options={'verbose_name': '导航页面', 'verbose_name_plural': '导航页面'},
        ),
        migrations.AlterField(
            model_name='page_info',
            name='p_stats',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0, max_length=1, verbose_name='页面状态'),
        ),
    ]
