# Generated by Django 3.2.3 on 2021-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0003_auto_20210524_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_info',
            name='p_types',
            field=models.IntegerField(choices=[(0, '未分类'), (1, '账号管理'), (2, '开发类'), (3, '运维类')], default=0, max_length=1, verbose_name='页面类别'),
        ),
    ]
