# Generated by Django 3.2.3 on 2021-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0004_page_info_p_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_info',
            name='p_stats',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0, verbose_name='页面状态'),
        ),
        migrations.AlterField(
            model_name='page_info',
            name='p_types',
            field=models.IntegerField(choices=[(0, '未分类'), (1, '账号管理'), (2, '开发类'), (3, '运维类')], default=0, verbose_name='页面类别'),
        ),
    ]
