# Generated by Django 3.2.3 on 2021-05-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0005_auto_20210524_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_info',
            options={'verbose_name': '页面信息', 'verbose_name_plural': '页面信息'},
        ),
        migrations.AddField(
            model_name='page_info',
            name='p_img',
            field=models.CharField(default='', max_length=100, verbose_name='图片路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page_info',
            name='p_gov',
            field=models.CharField(default='官网地址', max_length=100, verbose_name='官网地址'),
        ),
        migrations.AlterField(
            model_name='page_info',
            name='p_id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
