# Generated by Django 3.2.3 on 2021-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0006_auto_20210525_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_info',
            name='p_img',
            field=models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='图片路径'),
        ),
    ]
