# Generated by Django 3.2.3 on 2021-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0007_alter_page_info_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_info',
            name='p_img',
            field=models.ImageField(upload_to='ico/%Y/%m/%d/', verbose_name='图片路径'),
        ),
    ]
